version: '3.9'
services:

  rdb:
    container_name: db_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: ${RDB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${RDB_PASSWORD}
      MYSQL_DATABASE: webshop
    command: --init-file /data/application/init.sql
    ports:
      - ${RDB_PORT}:3306
    volumes:
      - type: volume
        source: data_rdb
        target: /var/lib/mysql
      - ./conf/mysql/init.sql:/data/application/init.sql

  webshop:
    container_name: webshop_container
    restart: always
    environment:
      RDB_USERNAME: ${RDB_USERNAME}
      RDB_PASSWORD: ${RDB_PASSWORD}
      DOCKER_ENV_SET_PROD: ""
      PUBLIC_JWT_TOKEN_SECRET: ${PUBLIC_JWT_TOKEN_SECRET}
      PSP_HOST: ${PSP_HOST}
      PSP_PORT: ${PSP_PORT}
      RDB_PORT: ${RDB_PORT}
      DB_SEC_ENC: ${DB_SEC_ENC}
    build:
      context: .
      dockerfile: GoBuild.dockerfile
      args:
        ARG_TARGET_GO: webshop
      target: image
    volumes:
      - ./common_pass.txt:/ubiquitous-payment/common_pass.txt
      - ../staticdata:/staticdata
      - ../logs:/logs
      - ./conf/certs/key/webshop.key.pem:/ubiquitous-payment/conf/certs/key/webshop.key.pem
      - ./conf/certs/pem/webshop.cert.pem:/ubiquitous-payment/conf/certs/pem/webshop.cert.pem
    ports:
      - 1080:8080
    depends_on:
      - rdb

  webshop_static:
    container_name: webshop_frontend
    restart: always
    build:
      context: .
      dockerfile: StaticBuild.dockerfile
      target: static
      args:
        WEBSHOP_SERVER_HOST_PORT: "host2:1080"
        PSP_SERVER_HOST_PORT: "host1:1081"
        BANK_SERVER_HOST_PORT: "host1:10001"
        WEBSHOP_PROTOCOL: "https"
        BANK_PROTOCOL: "https"
        PROTOCOL: "https"
        ARG_TARGET_STATIC: "webshop-front"
    ports:
      - 3000:443
    volumes:
      - ./conf/certs/pem/webshop.cert.pem:/etc/nginx/ssl/static.cert.pem
      - ./conf/certs/key/webshop.key.pem:/etc/nginx/ssl/static.key.pem
      - ./conf/static.nginx.conf:/etc/nginx/conf.d/default.conf


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data_rdb: