//export let WSserver = 'localhost:8001'
//export let PSPserver = 'localhost:8002'
export let WSserver = '$WEBSHOP_SERVER_HOST_PORT'
export let PSPserver = '$PSP_SERVER_HOST_PORT'
export let Protocol = 'kurcinela'
